version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_go_postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: host
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
