version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_go_postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: host
      POSTGRES_PASSWORD: postgres
    ports:
      - "5437:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  my_go_app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/go/src/app

volumes:
  postgres_data:
